#
# Copyright Super iPaaS Integration LLC, an IBM Company 2024
#
kind: Transport
apiVersion: api.webmethods.io/beta
metadata:
  name: transport
  namespace: dev_iam
  version: alpha
  tags:
    - transport
spec:
  protocol:
    - http